# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Estimator
                                 A QGIS plugin
 Tools untuk mengestimasi PBB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-08
        copyright            : (C) 2025 by UGM
        email                : ugm
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'UGM'
__date__ = '2025-06-08'
__copyright__ = '(C) 2025 by UGM'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Estimator class from file Estimator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .estimator import EstimatorPlugin
    return EstimatorPlugin()
